### ISSUE TITLE
Deprecation warning in code

### ISSUE THREAD

**Issue by fefoweb** [imsky/jquery-ui-bundle#1]
Hi, 

Using jquery-migrate to discover some potentially warning/deprecation in my project i found some deprecation message in jquery-ui-bundle
- JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos
- JQMIGRATE: jQuery.expr.filters is deprecated; use jQuery.expr.pseudos

jQuery version 3.2.1
jQuery-ui-bundle 1.12.1

I know that is a minor fix, but can be usefull :)
thanks

**Comment by imsky** [comment]
ok will take a look, thanks

**Comment by fefoweb** [comment]
If you want i can make a PR for fixing it...

**Comment by imsky** [comment]
the source here is automatically generated, i think this will be fixed once i regenerate it

let me check and i'll get back to you

**Comment by imsky** [comment]
turns out there isn't a newer jQuery UI release

fixed the issues you mentioned and another one (unique->uniqueSort)
